"use client";

import { FormEvent, useState } from "react";
import styles from "./page.module.css";
import { AdminRecordEdit } from "./admin-record-edit";

type Society = { name: string; registrationNo: string | null; address: string | null; currency: string } | null;
type Block = { id: string; name: string; description: string | null; status: string };
type Staff = { id: string; name: string; role: string; phone: string | null; salary: number | null; status: string };
export function AdminDataManager({ society, blocks: initialBlocks, staff: initialStaff }: { society: Society; blocks: Block[]; staff: Staff[] }) {
  const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>, type: string, id?: string) { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin", { method: id || type === "society" ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, type, id }) }); setMessage(response.ok ? "Saved successfully." : "Could not save this record."); if (response.ok) window.location.reload(); }
  async function deactivate(type: string, id: string) { if (!window.confirm("Deactivate this record? Existing financial history will be preserved.")) return; await fetch("/api/admin", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, id }) }); window.location.reload(); }
  const blocks = initialBlocks;
  const staff = initialStaff;
  return <div className={styles.adminGrid}>
    <section className={styles.adminCard}><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Society</p><h3>Identity & defaults</h3></div></div><form className={styles.adminForm} onSubmit={(event) => save(event, "society")}><label>Name<input name="name" defaultValue={society?.name ?? "Drishti Abasan"} required /></label><label>Registration number<input name="registrationNo" defaultValue={society?.registrationNo ?? ""} /></label><label>Address<input name="address" defaultValue={society?.address ?? ""} /></label><button className={styles.primaryButton}>Save society</button></form></section>
    <section className={styles.adminCard}><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Property structure</p><h3>Blocks</h3></div><span className={styles.successBadge}>{blocks.filter((item) => item.status === "ACTIVE").length} active</span></div><form className={styles.adminForm} onSubmit={(event) => save(event, "block")}><label>New block name<input name="name" placeholder="A" required /></label><label>Description<input name="description" placeholder="North wing" /></label><button className={styles.secondaryButton}>＋ Add block</button></form><div className={styles.adminList}>{blocks.map((block) => <div key={block.id}><span><strong>{block.name}</strong><small>{block.description ?? ""} · {block.status}</small></span><span className={styles.adminRowActions}>{block.status === "ACTIVE" && <><AdminRecordEdit type="block" id={block.id} name={block.name} description={block.description ?? ""} /><button className={styles.voidButton} onClick={() => deactivate("block", block.id)}>Deactivate</button></>}</span></div>)}</div></section>
    <section className={styles.adminCard}><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Operations</p><h3>Vendors & staff</h3></div><span className={styles.successBadge}>{staff.filter((item) => item.status === "ACTIVE").length} active</span></div><form className={styles.adminForm} onSubmit={(event) => save(event, "vendor")}><label>Name<input name="name" placeholder="Vendor or staff name" required /></label><div className={styles.formRow}><label>Role<select name="role" defaultValue="OTHER"><option>SECURITY_GUARD</option><option>SWEEPER</option><option>ELECTRICIAN</option><option>LIFT_AGENCY</option><option>OTHER</option></select></label><label>Phone<input name="phone" placeholder="Optional" /></label></div><label>Monthly salary<input name="monthlySalary" type="number" min="0" placeholder="Optional" /></label><button className={styles.secondaryButton}>＋ Add vendor/staff</button></form><div className={styles.adminList}>{staff.map((person) => <div key={person.id}><span><strong>{person.name}</strong><small>{person.role.replaceAll("_", " ")} · {person.status}</small></span><span className={styles.adminRowActions}>{person.status === "ACTIVE" && <><AdminRecordEdit type="vendor" id={person.id} name={person.name} role={person.role} phone={person.phone ?? ""} monthlySalary={person.salary ?? 0} /><button className={styles.voidButton} onClick={() => deactivate("vendor", person.id)}>Deactivate</button></>}</span></div>)}</div></section>{message && <p className={styles.formMessage}>{message}</p>}
  </div>;
}